### ISSUE TITLE
Task:  Create user stories for FTU, RU, SO

### ISSUE THREAD

**Issue by DeeMcCart** [Kaylaesmith1/budget_busters#47]
Task:  Create user stories for FTU (First-time users), RU (Retuning Users), SO (Systm Owner)

**Task Details**:
User Stories are needed:
* To add to READme under UX section;
* To ensure our app is developed to align with user's needs (each user story becomes a project issue assigned to a hackathon team member)
* To add to READme under Features section - each feature must identify the user stories it adresses
* To document testing, for Testing section of READme;

**Acceptance Criteria:**
- [x] Provisional list of user stories created (Saturday)
- [x] Each User Story created as a project issue (Saturday)
- [x] All User Stories added in UX section of READme with their relevant issue # (this will hyperlink within the readme) (Sat/Sun)
- [ ] User Stories cross-checked against Features in READme (Sat/Sun)
- [ ] User Stories are each tested and documentation created in Testing section of READme (Sunday)

**Comment by DeeMcCart** [comment]
Initial (proposed) list of User Stories:
**FTU**:
FTU01 As a **first-time user** I want to **quickly understand the site purpose** so I **can decide whether to spend time exploring and discovering the site**
FTU02 As a **first-time user** I want to **easily navigate the site** so I **don't become frustrated and leave**
FTU03 As a **first-time user** I want to **be able to navigate the site without mandatory login** so **I can discover site features before deciding whether to commit to using site**
FTU04 As a **first-time user** I want to **increase my financial awareness** to **improve my personal financial circumstances**
FTU05 As a **first-time user** I want to **access this site on a device of my choosing (mobile, tablet, laptop, desktop)** so that I can **access by a method and at a time that is convenient and accessible to me**

**Returning User:**
RU01 As  a **returning user** I want to **enter my financial goals** so I can **target what's important to me personally**
RU02 As a  *returning user** I want to **create a spending diary** so I can **track my spending over time**
RU03 As a *returning user** I want to **save data under my username** so I can **access my saved goals and spending history on subsequent site visits**
RU04 As a **returning user** I want to **set a monthly spending budget** so I **know what amount is available to me**
RU05 As a **returning user** I want to **see a breakdown of my spending by category** so I can **gain insights into my spending**
RU06 As a **returning user** I want to **see insights and trends of my spending** so I can **adjust my spending behaviour**
RU07 As a **returning user** I want to **track my progress against financial goals** so I can **adjust my spending behaviour if not meeting my goals**

System Owner: SO:
SO01 As **System Owner** I **want to provide a system that is easy to use** to **encourage users to visit and return to the site**
SO02 As **System Owner** I **want to provide responsive web pages** to **encourage users to use the site across multiple devices**
SO03 As **System Owner** I **want to provide interesting analysis and insights** to **increase user engagement with site**
SO04 As **System Owner** I want to **provide a low-cost website that can be implemented quickly** to **deliver this project**
SO05 
SO03 As **System Owner** I want to **provide informative content** to **increase user's financial literacy and awareness**
